from .bolsones import Bolsones as BolsonesResource
from .bolsones import Bolson as BolsonResource
from .bolsonesenventa import Bolsonesenventa as BolsonesenventaResource
from .bolsonesenventa import Bolsonenventa as BolsonenventaResource
from .bolsonespendientes import Bolsonespendientes as BolsonesPendiestesResource
from .bolsonpendientes import Bolsonpendiente as BolsonPendienteResource
from .bolsonesprevios import Bolsonesprevios as BolsonesPreviosResource
from .bolsonesprevios import Bolsonprevio as BolsonPrevioResource
from .productos import Productos as ProductosResource
from .productos import producto as ProductoResource
from .clientes import Clientes as ClientesResource
from .clientes import Cliente as ClientesResource
from .compras import Compras as ComprasResource
from .compras import Compra as CompraResource
from .proveedores import Proveedores as ProveedoresResource
from .proveedores import Proveedor as ProveedorResource
