from .bolsones import Bolsones as BolsonesResource
from .bolsones import Bolson as BolsonResource
from .bolsonesventa import BolsonesVenta as BolsonesVentaResource
from .bolsonesventa import BolsonVenta as BolsonVentaResource
from .bolsonespendientes import BolsonesPendientes as BolsonesPendientesResource
from .bolsonespendientes import BolsonPendiente as BolsonPendienteResource
from .bolsonesprevios import BolsonesPrevios as BolsonesPreviosResource
from .bolsonesprevios import BolsonPrevios as BolsonPreviosResource
from .productos import Productos as ProductosResource
from .productos import Producto as ProductoResource
from .clientes import Clientes as ClientesResource
from .clientes import Cliente as ClienteResource
from .compras import Compras as ComprasResource
from .compras import Compra as CompraResource
from .proveedores import Proveedores as ProveedoresResource
from .proveedores import Proveedor as ProveedorResource
